#:schema ../schema.json

[machine]
computer_name = "Wills-MacBook-Air"
type          = "apple-silicon"
username      = "will.ext"

[user]
name   = "Will Corrigan"
email  = "will-corrigan@users.noreply.github.com"
ssh_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHx5824VO9jx/mjYyVW8dcxywMn4dSk5KEbD3Eq2kCJ8"

[appearance]
font      = "monaspace-neon"
theme     = "catppuccin-mocha"
wallpaper = "default"

[programs]
zsh      = "curated"
starship = "curated"
fzf      = "curated"
bat      = "curated"
btop     = "curated"
ghostty  = "curated"
zed      = "curated"
tmux     = "curated"
git      = "curated"
direnv   = "curated"
zoxide   = "curated"
mise     = "curated"

[integrations]
ssh_signing = "1password"

[extra_packages]
cli   = ["_1password-cli", "awscli", "bruno", "eza", "fd", "flyctl", "glow", "jq", "k9s", "kubectl", "deadnix", "nixd", "nh", "nixfmt", "statix", "p7zip", "ripgrep", "sqlite", "terraform-ls", "tldr", "tree", "vim", "wget", "yq"]
brews = ["mise"]
casks = ["1password", "claude-code", "discord", "ghostty", "google-chrome", "gcloud-cli", "rancher", "raycast", "slack", "spotify", "visual-studio-code", "zed"]

[macos.keyboard]
caps_lock    = "escape"
key_repeat   = "fast"
repeat_delay = "short"

[macos.dock]
position        = "bottom"
icon_size       = "medium"
auto_hide       = true
minimize_to_app = true

[macos.finder]
default_view    = "list"
show_extensions = true
show_path_bar   = false
show_hidden     = true

[macos.trackpad]
tap_to_click   = true
natural_scroll = false
